source 'https://rubygems.org'

gem 'rails', '~> 3.2.3'
gem 'mysql2'
gem 'jquery-rails'
gem 'haml'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'therubyracer', :platform => :ruby
  gem 'uglifier', '>= 1.0.3'
end
